name       : lightdm
version    : 1.26.0
release    : 29
source     :
    - https://github.com/CanonicalLtd/lightdm/releases/download/1.26.0/lightdm-1.26.0.tar.xz : c95e14e9131b5f95ecba42faaab2cfa917371193caa54fa1b4322ad7a89334f0
homepage   : https://github.com/CanonicalLtd/lightdm
license    :
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : desktop.lightdm
conflicts  :
    - gdm
    - sddm
summary    : Lightweight and attractive Display Manager
description: |
    Lightweight and attractive Display Manager
builddeps  :
    - pkgconfig(libxklavier)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(yelp-xsl)
    - itstool
    - libgcrypt-devel
    - vala
    - yelp-devel
    - yelp-tools
rundeps    :
    - linux-driver-management-lightdm-integration
    - setxkbmap
    - xauth
    - xhost
    - xkbcomp
    - xkeyboard-config
setup      : |
    sed -i -e 's:getgroups:lightdm_&:' tests/src/libsystem.c
    %apply_patches
    %reconfigure --enable-introspection \
                 --disable-static \
                 --disable-tests \
                 --libexecdir=%libdir%/lightdm \
                 --with-greeter-session=lightdm-gtk-greeter
build      : |
    %make -j1
install    : |
    %make_install
    install -d -m 00755 $installdir/%libdir%/systemd/system/graphical.target.wants
    ln -s %libdir%/systemd/system/lightdm.service $installdir/%libdir%/systemd/system/displaymanager.service
    ln -s %libdir%/systemd/system/lightdm.service $installdir/%libdir%/systemd/system/graphical.target.wants/lightdm.service
    # Stateless configuration
    rm -rf $installdir/etc/lightdm
    # We don't use apparmor
    rm -rf $installdir/etc/init
    rm -rf $installdir/etc/apparmor.d
    install -m 00644 $pkgfiles/lightdm.service $installdir/%libdir%/systemd/system/lightdm.service
    install -D -m 00755 $pkgfiles/lightdm-wrapper $installdir/usr/bin/lightdm-wrapper
    install -D -m 00644 $pkgfiles/lightdm.conf $installdir/usr/share/lightdm/lightdm.conf.d/10_solus_default.conf
    install -m 00644 $pkgfiles/users.conf $installdir/usr/share/lightdm/users.conf

    install -D -m 00644 $pkgfiles/lightdm.tmpfiles $installdir/%libdir%/tmpfiles.d/lightdm.conf
    install -D -m 00644 $pkgfiles/lightdm.sysusers $installdir/%libdir%/sysusers.d/lightdm.conf
    install -Dm 00644 $pkgfiles/lightdm.pam $installdir/etc/pam.d/lightdm
    install -Dm 00644 $pkgfiles/lightdm-greeter.pam $installdir/etc/pam.d/lightdm-greeter
