name       : lightdm
version    : 1.24.0
release    : 19
source     :
    - https://launchpad.net/lightdm/1.24/1.24.0/+download/lightdm-1.24.0.tar.xz : cd509b74382bcf382c6e3e4b54ac30ba804022fec968d6993d134552ea1a43a2
homepage   : https://launchpad.net/lightdm
license    : GPL-3.0
component  : desktop.lightdm
conflicts  :
    - gdm
    - sddm
summary    : Lightweight and attractive Display Manager
builddeps  :
    - pkgconfig(libxklavier)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(yelp-xsl)
    - libgcrypt-devel
    - itstool
    - yelp-tools
    - yelp-devel
rundeps    :
    - linux-driver-management-lightdm-integration
description: |
    Lightweight and attractive Display Manager
setup      : |
    sed -i -e 's:getgroups:lightdm_&:' tests/src/libsystem.c
    %apply_patches
    %reconfigure --enable-introspection \
                 --enable-liblightdm-gobject \
                 --disable-static \
                 --disable-tests \
                 --libexecdir=%libdir%/lightdm \
                 --with-greeter-session=lightdm-gtk-greeter
    #sed -i /YELP_HELP_RULES/d help/Makefile
build      : |
    %make -j1
install    : |
    %make_install
    install -d -D -m 00755 $installdir/%libdir%/systemd/system/graphical.target.wants
    ln -s %libdir%/systemd/system/lightdm.service $installdir/%libdir%/systemd/system/displaymanager.service
    ln -s %libdir%/systemd/system/lightdm.service $installdir/%libdir%/systemd/system/graphical.target.wants/lightdm.service
    # Stateless configuration
    rm -rf $installdir/etc/lightdm
    # We don't use apparmor
    rm -rf $installdir/etc/init
    rm -rf $installdir/etc/apparmor.d
    install -D -m 00644 $pkgfiles/lightdm.service $installdir/%libdir%/systemd/system/lightdm.service
    install -D -m 00755 $pkgfiles/lightdm-wrapper $installdir/usr/bin/lightdm-wrapper
    install -D -m 00644 $pkgfiles/lightdm.conf $installdir/usr/share/lightdm/lightdm.conf.d/10_solus_default.conf
    install -D -m 00644 $pkgfiles/users.conf $installdir/usr/share/lightdm/users.conf

    install -D -m 00644 $pkgfiles/lightdm.tmpfiles $installdir/%libdir%/tmpfiles.d/lightdm.conf
    install -D -m 00644 $pkgfiles/lightdm.sysusers $installdir/%libdir%/sysusers.d/lightdm.conf
