name       : lightdm
version    : 1.32.0
release    : 42
source     :
    - https://github.com/canonical/lightdm/archive/refs/tags/1.32.0.tar.gz : 6dbcd58332abdc113a7a345c22027c9e485ada802706c6b7fbf5f410464e53e3
homepage   : https://github.com/CanonicalLtd/lightdm
license    :
    - LGPL-3.0-or-later
    - GPL-3.0-or-later
component  : desktop.lightdm
conflicts  :
    - gdm
    - sddm
summary    : Lightweight and attractive Display Manager
description: |
    Lightweight and attractive Display Manager
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(libxklavier)
    - pkgconfig(x11)
    - pkgconfig(xcb)
    - pkgconfig(xdmcp)
    - pkgconfig(yelp-xsl)
    - gtk-doc
    - itstool
    - vala
    - yelp-devel
    - yelp-tools
rundeps    :
    - linux-driver-management-lightdm-integration
    - setxkbmap
    - xauth
    - xhost
    - xkbcomp
    - xkeyboard-config
setup      : |
    sed -i -e 's:getgroups:lightdm_&:' tests/src/libsystem.c
    %apply_patches
    %reconfigure --enable-introspection \
                 --disable-static \
                 --disable-tests \
                 --enable-gtk-doc \
                 --libexecdir=%libdir%/lightdm \
                 --with-greeter-session=lightdm-gtk-greeter
build      : |
    %make -j1
install    : |
    %make_install
    install -dm00755 $installdir/%libdir%/systemd/system/graphical.target.wants
    ln -s %libdir%/systemd/system/lightdm.service $installdir/%libdir%/systemd/system/display-manager.service
    ln -s %libdir%/systemd/system/lightdm.service $installdir/%libdir%/systemd/system/graphical.target.wants/lightdm.service
    # Stateless configuration
    rm -rf $installdir/etc/lightdm
    # We don't use apparmor
    rm -rf $installdir/etc/init
    rm -rf $installdir/etc/apparmor.d
    install -m00644 $pkgfiles/lightdm.service $installdir/%libdir%/systemd/system/lightdm.service
    install -Dm00755 $pkgfiles/lightdm-wrapper $installdir/usr/bin/lightdm-wrapper
    install -Dm00644 $pkgfiles/lightdm.conf $installdir/usr/share/lightdm/lightdm.conf.d/10_solus_default.conf
    install -m00644 $pkgfiles/users.conf $installdir/usr/share/lightdm/users.conf

    install -Dm00644 $pkgfiles/lightdm.tmpfiles $installdir/%libdir%/tmpfiles.d/lightdm.conf
    install -Dm00644 $pkgfiles/lightdm.sysusers $installdir/%libdir%/sysusers.d/lightdm.conf

    install -d $installdir/usr/share/defaults
    mv $installdir{,/usr/share/defaults}/etc
    install -Dm00644 $pkgfiles/lightdm.pam $installdir/usr/share/defaults/etc/pam.d/lightdm
    install -Dm00644 $pkgfiles/lightdm-greeter.pam $installdir/usr/share/defaults/etc/pam.d/lightdm-greeter
